name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: 'true'
    name: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.18
      - name: Install
        run: yarn
      - name: Configure amplify
        run: npm i -g @aws-amplify/cli && amplify env checkout dev
      - name: Build
        run: CI=true yarn build
      - name: Cache Repo
        uses: actions/cache@v1
        id: cache-build
        with:
          path: '.'
          key: ${{ github.sha }}
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      CI: 'true'
    if: github.ref == 'refs/heads/master'
    name: Publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache Repo
        uses: actions/cache@v1
        id: cache-build
        with:
          path: '.'
          key: ${{ github.sha }}
      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.18
      - name: Install
        run: yarn
      - name: Configure amplify
        run: npm i -g @aws-amplify/cli && amplify env checkout dev
      - name: Publish to Amplify
        uses: mujo-code/puppeteer-headful@master
        with:
          args: yarn publish

