name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.18
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master'
    name: Publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.18
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish
        run: npm run amplify:publish

